[package]
name = "drive"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[features]
default = ["desktop"]
desktop = ["wgame/desktop"]
web = ["wgame/web"]

[dependencies]
wgame = { path = "wgame/wgame", default-features = false, features = ["3d", "image"] }
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
rand = { version = "0.9.2", default-features = false, features = ["alloc", "small_rng"] }
tobj = { version = "4.0.3", default-features = false }
anyhow = "1.0.100"
phy = { path = "phy" }
glam = { version = "0.33.7", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
wgpu = { version = "30.0.1", default-features = false }
futures = { version = "0.3.34", features = ["executor"] }
